# Generated by Django 3.1.4 on 2020-12-15 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201214_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lastupdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 2, 2, 7, 890069, tzinfo=utc)),
        ),
    ]
