# Generated by Django 3.1.4 on 2020-12-15 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201215_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lastupdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 23, 43, 33, 288538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(default='ffffff', max_length=10),
        ),
    ]
