# Generated by Django 3.1.4 on 2020-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20201210_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='area',
            field=models.CharField(choices=[('LG', 'language'), ('SO', 'software')], default='LG', max_length=2),
        ),
    ]
